/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_D1_aliases.h"
#include "Pin_D1.h"
#include "Pin_D2_aliases.h"
#include "Pin_D2.h"
#include "Pin_D3_aliases.h"
#include "Pin_D3.h"
#include "Pin_D4_aliases.h"
#include "Pin_D4.h"
#include "Pin_SW1_aliases.h"
#include "Pin_SW1.h"
#include "Pin_SW2_aliases.h"
#include "Pin_SW2.h"
#include "Pin_SW3_aliases.h"
#include "Pin_SW3.h"
#include "Pin_SW4_aliases.h"
#include "Pin_SW4.h"
#include "LCD_Screen.h"
#include "ROW0_aliases.h"
#include "ROW0.h"
#include "ROW1_aliases.h"
#include "ROW1.h"
#include "ROW2_aliases.h"
#include "ROW2.h"
#include "ROW3_aliases.h"
#include "ROW3.h"
#include "COL1_aliases.h"
#include "COL1.h"
#include "COL2_aliases.h"
#include "COL2.h"
#include "COL3_aliases.h"
#include "COL3.h"
#include "ADC_DelSig.h"
#include "Pin_Pot_aliases.h"
#include "Pin_Pot.h"
#include "AMux.h"
#include "Pin_photoresistor_aliases.h"
#include "Pin_photoresistor.h"
#include "Timer.h"
#include "VDAC.h"
#include "DAC_OUT_aliases.h"
#include "DAC_OUT.h"
#include "UART.h"
#include "Pin_Servo1_aliases.h"
#include "Pin_Servo1.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "Pin_Servo2_aliases.h"
#include "Pin_Servo2.h"
#include "PWM_2.h"
#include "Clock_2.h"
#include "Rx_Int.h"
#include "LCD_Screen_LCDPort_aliases.h"
#include "LCD_Screen_LCDPort.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

